# Generated by Django 4.0.2 on 2022-02-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alter', models.CharField(max_length=80)),
                ('geburtssort', models.CharField(max_length=80)),
                ('wohnort', models.CharField(max_length=80)),
            ],
        ),
    ]
