# Generated by Django 4.0.2 on 2022-02-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_rename_dataset_personalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='geburtssort',
            new_name='geburtsort',
        ),
    ]
