# Generated by Django 4.0.2 on 2022-02-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_rename_geburtssort_personalinfo_geburtsort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='alter',
            new_name='Alter',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='geburtsort',
            new_name='Geburtsort',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='wohnort',
            new_name='Wohnort',
        ),
    ]
