# Generated by Django 4.0.2 on 2022-02-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_rename_alter_personalinfo_alter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personalInfo',
            new_name='userData',
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User Data'},
        ),
    ]
