# Generated by Django 4.0.2 on 2022-02-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_rename_personalinfo_userdata_alter_userdata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userData',
        ),
    ]
